### ISSUE TITLE
combine csvs - 1 and 2 for each region

### ISSUE THREAD

**Issue by AntonyUsoltsev** [Alex1um/agroVision#10]
В двух папках лежат таблицы но одна csv с запятой разделителем, а другие excel. Надо перегнать все в один csv с запятой разделителем

**Comment by AntonyUsoltsev** [comment]
Таблицы неправильно склеились

**Comment by AntonyUsoltsev** [comment]
Task:
1) Заново обьединить две таблицы, потому что в первый раз прочитались значения из 4 последних строк в первой таблице (возможно их стоит удалить чтобы совсем не мешались).
2) Если не получится кодом то вручную
3) строка должна иметь вид TOGUCHI,55.2167,84.3667,01/05/2022,16.0,7.5,0.0,39.0,3.4 где в полях не желательно больше 2 цифр после запятой (ВНИМАНИЕ на дату (развернуть день-месяц-год если выйдет, но возможно не критично))
4) в каждом полученном csv файле должно быть 123 строки
5) Переделать парсинг csv в классе data, убрать код склейки таблиц (сейчас там почему то парсинг экселя)

**Comment by Alex1um** [comment]
1, 2, 4. все таблички 123 строки.
3. Ну оно такое. воообще исходный вид не имеет значения. Если нужно, можно отрезать при вычислении, так даже правельнее будет. Темболее он уже таким пришел.
5.
>сейчас там почему то парсинг экселя

??? нет там ничего
Куда переделывать? только убрать if на табы?
