### ISSUE TITLE
Стек технологий

### ISSUE THREAD

**Issue by Alex1um** [Alex1um/agroVision#12]
Нужно по итогу определиться со стеком. Так как обычный python - совсем не то как будто бы.
Я вижу следущие опции:
* Sympy - штука работает с символьными формулами. С ним можно просто переписать все формулы напрямую из matcad абсолюдно теми же символами и дальше просто подставить реальные данные при eval.
* Numpy - массивы и операции над ними. У нас по сути массивы данных и с numpy будет в 100 раз удобней, так как у него много встроенного добра, например чтобы умножить все элементы ма константу можно просто `array * const`, а не городить какие-то `map(lambda x: ...)`. + Код будет очень похож, чем есть сейчас, но будет гораздо чище.
* Есть всякие padas, apache arrow(pyarrow). Это прям работа с табличками. Не знаю насколько оно будет лучше того же numpy, но функционал примерно тот же.

**Comment by Alex1um** [comment]
Как будто бы интутивнее и лучше будет numpy. Но с sympy может оказаться проще и тупее

**Comment by Alex1um** [comment]
Вот например переписанная функция hut_count:
```py
# was
def hut_count(data):
    hut = []
    for dict in data:
        average_temp = (float(dict["max_temp"]) + float(dict["min_temp"])) / 2 - constants.constant_dict["Tb"]
        hut.append(average_temp if average_temp > 0 else 0)
    return hut
# numpy
def hut_count(data):
    max_temps = np.array([float(d["max_temp"]) for d in data])
    min_temps = np.array([float(d["min_temp"]) for d in data])
    average_temps = (max_temps + min_temps) / 2 - constants.constant_dict["Tb"]
    return np.maximum(average_temps, 0)
```
Он кстаи неправильный, так как неонятно, что в data

**Comment by AntonyUsoltsev** [comment]
С sympy может быть шляпа, потому что у нас по сути нет ни одной нормальной формулы, а писать новые математические формулы больше впадлу чем циклы
Но надо просто сделать один кусочек во всех вариациях и посмотреть

**Comment by AntonyUsoltsev** [comment]
> Вот например переписанная функция hut_count:
> 
> ```python
> # was
> def hut_count(data):
>     hut = []
>     for dict in data:
>         average_temp = (float(dict["max_temp"]) + float(dict["min_temp"])) / 2 - constants.constant_dict["Tb"]
>         hut.append(average_temp if average_temp > 0 else 0)
>     return hut
> # numpy
> def hut_count(data):
>     max_temps = np.array([float(d["max_temp"]) for d in data])
>     min_temps = np.array([float(d["min_temp"]) for d in data])
>     average_temps = (max_temps + min_temps) / 2 - constants.constant_dict["Tb"]
>     return np.maximum(average_temps, 0)
> ```
> 
> Он кстаи неправильный, так как неонятно, что в data

В data массив словарей. Ну если честно выглядит модно, но чтобы понять пришлось потратить чуть больше времени

**Comment by Alex1um** [comment]
> > Вот например переписанная функция hut_count:
> > ```python
> > # was
> > def hut_count(data):
> >     hut = []
> >     for dict in data:
> >         average_temp = (float(dict["max_temp"]) + float(dict["min_temp"])) / 2 - constants.constant_dict["Tb"]
> >         hut.append(average_temp if average_temp > 0 else 0)
> >     return hut
> > # numpy
> > def hut_count(data):
> >     max_temps = np.array([float(d["max_temp"]) for d in data])
> >     min_temps = np.array([float(d["min_temp"]) for d in data])
> >     average_temps = (max_temps + min_temps) / 2 - constants.constant_dict["Tb"]
> >     return np.maximum(average_temps, 0)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Он кстаи неправильный, так как неонятно, что в data
> 
> В data массив словарей. Ну если честно выглядит модно, но чтобы понять пришлось потратить чуть больше времени
```py
for dict in data:
        average_temp = (float(dict["max_temp"]) + float(dict["min_temp"])) / 2 - constants.constant_dict["Tb"]
```
Ну вот например что здесь происходит я не понимаю совсем, особенно вот эти конвертации в float. и какие-то обращения к словарям.
Наверное, если сделать столбцы массивами numpy, может сократиться вообще до такого:
```py
def hut_count(max_temps: np.ndarray, min_temps: np.ndarray):
    average_temps = (max_temps + min_temps) / 2 - constants.constant_dict["Tb"]
    return np.maximum(average_temps, 0) # for each element gets maximum between the element and 0
```

**Comment by AntonyUsoltsev** [comment]
> > > Вот например переписанная функция hut_count:
> > > ```python
> > > # was
> > > def hut_count(data):
> > >     hut = []
> > >     for dict in data:
> > >         average_temp = (float(dict["max_temp"]) + float(dict["min_temp"])) / 2 - constants.constant_dict["Tb"]
> > >         hut.append(average_temp if average_temp > 0 else 0)
> > >     return hut
> > > # numpy
> > > def hut_count(data):
> > >     max_temps = np.array([float(d["max_temp"]) for d in data])
> > >     min_temps = np.array([float(d["min_temp"]) for d in data])
> > >     average_temps = (max_temps + min_temps) / 2 - constants.constant_dict["Tb"]
> > >     return np.maximum(average_temps, 0)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Он кстаи неправильный, так как неонятно, что в data
> > 
> > 
> > В data массив словарей. Ну если честно выглядит модно, но чтобы понять пришлось потратить чуть больше времени
> 
> ```python
> for dict in data:
>         average_temp = (float(dict["max_temp"]) + float(dict["min_temp"])) / 2 - constants.constant_dict["Tb"]
> ```
> 
> Ну вот например что здесь происходит я не понимаю совсем, особенно вот эти конвертации в float. наверное, если сделать столбцы массивами numpy, может сократиться вообще до такого:
> 
> ```python
> def hut_count(max_temps: np.ndarray, min_temps: np.ndarray):
>     average_temps = (max_temps + min_temps) / 2 - constants.constant_dict["Tb"]
>     return np.maximum(average_temps, 0) # for each element gets maximum between the element and 0
> ```

Ну там парсер распарсил csv в словарь у которого значения строки, отсюда и float. Тут наверное проблема в том, чтобы изначально сделать хорошую коллекцию и потом  с ней удобно работать
