### ISSUE TITLE
Sun data

### ISSUE THREAD

**Issue by AntonyUsoltsev** [Alex1um/agroVision#17]

**Comment by AntonyUsoltsev** [comment]
Task:
1) Склеить данные о солнечной радиации из первого файла и второго в один файл csv
2) Строка должна представлять вид 01/05/2022,3.47
3) Код преобразования оставлять не нужно
4) Сделать класс который парсит полученный csv

**Comment by Alex1um** [comment]
> Склеить данные о солнечной радиации из первого файла и второго в один файл csv

в отдельное issue пожалуйста.

**Comment by Alex1um** [comment]
> * Склеить данные о солнечной радиации из первого файла и второго в один файл csv
> * Строка должна представлять вид 01/05/2022,3.47
> * Код преобразования оставлять не нужно
> * Сделать класс который парсит полученный csv

Новое issue создано #21
