### ISSUE TITLE
Склеить данные solar radiation

### ISSUE THREAD

**Issue by Alex1um** [Alex1um/agroVision#21]
Task:
1) Склеить данные о солнечной радиации из первого файла и второго в один файл csv
2) Строка должна представлять вид 01/05/2022,3.47
3) Код преобразования оставлять не нужно
4) Сделать класс который парсит полученный csv

_Originally posted by @AntonyUsoltsev in https://github.com/Alex1um/agroVision/issues/17#issuecomment-1785748763_

**Comment by Alex1um** [comment]
csv? еще один формат парсить?

**Comment by AntonyUsoltsev** [comment]
тут теперь все надо парсить.. И первый файл кривой и эксельчик из второй части

**Comment by Alex1um** [comment]
так а зачем это сохранять в csv, если она не приходит в таком формате?
