### ISSUE TITLE
Add constant fields

### ISSUE THREAD

**Issue by AntonyUsoltsev** [Alex1um/agroVision#8]

**Comment by AntonyUsoltsev** [comment]
Норм ли выкидывать исключение и закрывать программу если не хватает константы или ставить значение по дефолту;
Идея считать все словарь а затем попробовать сделать get, если упадет то значит нет константы 
for key in ["const_name1", "const_name2" ....]:
      try:
        value = const_dict[key]
    except KeyError:
        print(f"Константа '{key}' не найдена в таблице констант.")

**Comment by AntonyUsoltsev** [comment]
пока не придумал более адекватного способа 🤷‍♂️

**Comment by AntonyUsoltsev** [comment]
или хранить все в словаре но сделать к нему get с проверкой на существование такой константы, потому что вдруг не все константы используются

**Comment by Alex1um** [comment]
Наверное, если не хватает константы - логично завершать программу с ошибкой.
Насчет дефолтных значений: а они есть?

**Comment by Alex1um** [comment]
Насчет хранения: я все еще думаю нужен именно класс с константами. Если все константы уже известны, нужно сделать  их полями этого класса. Если нет, сделать внутри класса словарь и организовать обращение через класс.
Класс будет полезен, так как логику можно будет засунуть в него, а не раскидать по разным кускам.

**Comment by Alex1um** [comment]
В классе например можно сделать метод 
```py
@classmethod
def from_xl(cls, file):
    ...
```
И выбросить варнинги(пжлста через модуль logging) на все не считанные переменные.
Можно сделать некоторые переменные обязательными и завершать программу, если они не считались.

**Comment by Alex1um** [comment]
Просто в классе можно переопределить всякие операторы типа `.`, `in`, и т.д. и, например, выкидывать нормальные сообщения об ошибках
